version: "3"
services:
  ark:
    image: ghcr.io/ekman/ark:0.0.1
    build:
      context: .
    restart: unless-stopped
    read_only: true
    volumes: 
      - "./game:/home/steam/game"
      - "./config:/home/steam/game/ShooterGame/Saved/Config/LinuxServer"
    expose:
      - 27015:27015/udp
      - 7777-7778:7777-7778/udp
